server:
  port: 3800

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: Products
          uri: http://localhost:4100/
          predicates:
            - Path=/products/**
        - id: Cart
          uri: http://localhost:4000/
          predicates:
            - Path=/cart/**
        - id: Users
          uri: http://localhost:3900/
          predicates:
            - Path=/users/**